# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application-dev.yml file.
# ===================================================================

spring:
  profiles: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:32777/class?autoReconnect=true&useSSL=false
      username: docker
      password: docker