# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

spring:
  application:
    name: class-bot
  profiles:
    active: dev

server:
  port: 8080

management:
  port: 8090
  context-path: /management
  security:
    enabled: false