# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application-prod.yml file.
# ===================================================================

spring:
  profiles: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      jdbc-url: jdbc:pgjdbc-ng://$heroku_host:$heroku_port/class?autoReconnect=true&useSSL=false
      username: $herokuUserName
      password: $herokuPassword
#      data-source-class-name: org.postgresql.ds.PGSimpleDataSource