# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application-dev.yml file.
# ===================================================================

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:32775/class?autoReconnect=true&useSSL=false
      username: docker
      password: docker
#      data-source-class-name: org.postgresql.ds.PGSimpleDataSource